name: Immobilien Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Alle 5 Minuten
  workflow_dispatch:  # Ermöglicht manuelles Ausführen

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Erforderlich zum Pushen von Commits
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Run Scraper
        env:
          PROWL_API_KEY: ${{ secrets.PROWL_API_KEY }}  # GitHub Secret als Umgebungsvariable
        run: |
          python monitor.py
      - name: Commit and Push changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add immobilien_count.json
          git commit -m "Update immobilien_count.json with latest count" || echo "No changes to commit"
          git push
